spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

dubbo:
  application:
    name: dubbo-gateway
  protocol:
    name: dubbo
    port: 20880
  registry:
    id: nacos-registry
    address: nacos://localhost:8848