spring:
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guoapi?characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useUnicode=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&autoReconnect=true
    username: root
    password: 123
    hikari:
      max-lifetime: 120000
  # 本地 redis 配置
  redis:
    host: 101.43.124.198
    port: 6379
    password: 123
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
# RPC 框架
dubbo:
  scan:
    base-packages: com.edu.guoapi.service.provider
  application:
    name: guoapi-backend
  protocol:
    name: dubbo
    port: 20881
  registry:
    id: nacos-registry
    address: nacos://localhost:8848

# 自定义 SDK 的网关地址
guoapi:
  client:
    gateway-addr: http://127.0.0.1:9000